
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author famil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaCrear = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        labelnombre = new javax.swing.JLabel();
        NombreEquipo = new javax.swing.JTextField();
        guardarEquipo = new javax.swing.JButton();
        ventanaModificar = new javax.swing.JDialog();
        jLabeltextmod = new javax.swing.JLabel();
        tf_pos = new javax.swing.JTextField();
        butonmod = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelnombre1 = new javax.swing.JLabel();
        NombreEquipomod = new javax.swing.JTextField();
        guardarEquipo1 = new javax.swing.JButton();
        ventanaEliminar = new javax.swing.JDialog();
        jLabeltextmod1 = new javax.swing.JLabel();
        tf_posEl = new javax.swing.JTextField();
        butonmod1 = new javax.swing.JButton();
        ventanaCargarArchivo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablitaCarga = new javax.swing.JTable();
        ventanaSimular = new javax.swing.JDialog();
        boxEquipo1 = new javax.swing.JComboBox<>();
        boxEquipo2 = new javax.swing.JComboBox<>();
        golEquipo1 = new javax.swing.JLabel();
        golEquipo2 = new javax.swing.JLabel();
        botonSimular = new javax.swing.JButton();
        ventanaTabla = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barra = new javax.swing.JMenuBar();
        tabEquipos = new javax.swing.JMenu();
        Crear = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        cargarArchivo = new javax.swing.JMenuItem();
        tabPartidos = new javax.swing.JMenu();
        simulacion = new javax.swing.JMenuItem();
        tablaPosiciones = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Crear Equipos");

        labelnombre.setText("Nombre del Equipo");

        guardarEquipo.setText("Guardar");
        guardarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanaCrearLayout = new javax.swing.GroupLayout(ventanaCrear.getContentPane());
        ventanaCrear.getContentPane().setLayout(ventanaCrearLayout);
        ventanaCrearLayout.setHorizontalGroup(
            ventanaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaCrearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ventanaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaCrearLayout.createSequentialGroup()
                        .addComponent(labelnombre)
                        .addGap(18, 18, 18)
                        .addGroup(ventanaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaCrearLayout.createSequentialGroup()
                        .addComponent(guardarEquipo)
                        .addGap(159, 159, 159))))
        );
        ventanaCrearLayout.setVerticalGroup(
            ventanaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(ventanaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnombre)
                    .addComponent(NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardarEquipo)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabeltextmod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltextmod.setText("Ingrese la posicion del equipo a modificar");

        butonmod.setText("Ingresar");
        butonmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonmodMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese los nuevos valores");

        labelnombre1.setText("Nombre del Equipo");

        guardarEquipo1.setText("Guardar");
        guardarEquipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarEquipo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanaModificarLayout = new javax.swing.GroupLayout(ventanaModificar.getContentPane());
        ventanaModificar.getContentPane().setLayout(ventanaModificarLayout);
        ventanaModificarLayout.setHorizontalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltextmod, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ventanaModificarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(butonmod)
                                        .addComponent(tf_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelnombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreEquipomod, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(guardarEquipo1)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        ventanaModificarLayout.setVerticalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltextmod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonmod)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnombre1)
                    .addComponent(NombreEquipomod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardarEquipo1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabeltextmod1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltextmod1.setText("Ingrese la posicion del equipo a Eliminar");

        butonmod1.setText("Eliminar");
        butonmod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonmod1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanaEliminarLayout = new javax.swing.GroupLayout(ventanaEliminar.getContentPane());
        ventanaEliminar.getContentPane().setLayout(ventanaEliminarLayout);
        ventanaEliminarLayout.setHorizontalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tf_posEl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltextmod1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(butonmod1))
        );
        ventanaEliminarLayout.setVerticalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabeltextmod1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_posEl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonmod1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tablitaCarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablitaCarga);

        javax.swing.GroupLayout ventanaCargarArchivoLayout = new javax.swing.GroupLayout(ventanaCargarArchivo.getContentPane());
        ventanaCargarArchivo.getContentPane().setLayout(ventanaCargarArchivoLayout);
        ventanaCargarArchivoLayout.setHorizontalGroup(
            ventanaCargarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaCargarArchivoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        ventanaCargarArchivoLayout.setVerticalGroup(
            ventanaCargarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaCargarArchivoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        golEquipo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        golEquipo1.setText("0");

        golEquipo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        golEquipo2.setText("0");

        botonSimular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSimular.setText("Simular");
        botonSimular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSimularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanaSimularLayout = new javax.swing.GroupLayout(ventanaSimular.getContentPane());
        ventanaSimular.getContentPane().setLayout(ventanaSimularLayout);
        ventanaSimularLayout.setHorizontalGroup(
            ventanaSimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaSimularLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(boxEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(boxEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(ventanaSimularLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(golEquipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(golEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(ventanaSimularLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(botonSimular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaSimularLayout.setVerticalGroup(
            ventanaSimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaSimularLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(ventanaSimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEquipo1))
                .addGap(18, 18, 18)
                .addGroup(ventanaSimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(golEquipo1)
                    .addComponent(golEquipo2))
                .addGap(32, 32, 32)
                .addComponent(botonSimular)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout ventanaTablaLayout = new javax.swing.GroupLayout(ventanaTabla.getContentPane());
        ventanaTabla.getContentPane().setLayout(ventanaTablaLayout);
        ventanaTablaLayout.setHorizontalGroup(
            ventanaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTablaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        ventanaTablaLayout.setVerticalGroup(
            ventanaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTablaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabEquipos.setText("Equipos");

        Crear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N
        Crear.setText("Crear Equipo");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        tabEquipos.add(Crear);

        Modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificar.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        tabEquipos.add(Modificar);

        Eliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        tabEquipos.add(Eliminar);

        cargarArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CargarArchivo.png"))); // NOI18N
        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        tabEquipos.add(cargarArchivo);

        barra.add(tabEquipos);

        tabPartidos.setText("Partidos");

        simulacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        simulacion.setText("Simular");
        simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulacionActionPerformed(evt);
            }
        });
        tabPartidos.add(simulacion);

        tablaPosiciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        tablaPosiciones.setText("Tabla de Posiciones");
        tablaPosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaPosicionesActionPerformed(evt);
            }
        });
        tabPartidos.add(tablaPosiciones);

        barra.add(tabPartidos);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        ejecutarCrear();
        
    }//GEN-LAST:event_CrearActionPerformed

    private void guardarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarEquipoMouseClicked
        // TODO add your handling code here:
         EquiposFutbol team=new EquiposFutbol(NombreEquipo.getText(),0,0,0,0,0,0,0,0);
         if(verificarNombre(NombreEquipo.getText())){
             JOptionPane.showMessageDialog(this, "Dos equipos no pueden tener el mismo nombre ");
           NombreEquipo.setText("");
         }
         equipos.add(team);
         DefaultComboBoxModel comb=(DefaultComboBoxModel) boxEquipo1.getModel();
          DefaultComboBoxModel comb2=(DefaultComboBoxModel) boxEquipo2.getModel();
          
          for (EquiposFutbol teamChamp : equipos) {
            comb.addElement(teamChamp.getNombre());
         comb2.addElement(teamChamp.getNombre());
        }
         boxEquipo1.setModel(comb);
         boxEquipo2.setModel(comb2);
         NombreEquipo.setText("");
        
        try {
         
         administrarUser.setChampions(equipos);
            administrarUser.escribirText();
            JOptionPane.showMessageDialog(this, "Equipo agregado Exitosamente");
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this, "Nose puede agregar el Equipo");
        }
        
         
    }//GEN-LAST:event_guardarEquipoMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        ejecutarModificar();
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void butonmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonmodMouseClicked
        // TODO add your handling code here:
        int pos = Integer.parseInt(tf_pos.getText());
    }//GEN-LAST:event_butonmodMouseClicked

    private void guardarEquipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarEquipo1MouseClicked
        // TODO add your handling code here:
        int pos = Integer.parseInt(tf_pos.getText());
        equipos.get(pos).setNombre(NombreEquipomod.getText());
        try {             
         administrarUser.setChampions(equipos);
         administrarUser.escribirText();
            JOptionPane.showMessageDialog(this, "Equipo modificado Exitosamente");
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this, "Nose puede agregar el Equipo");
        }
        
    }//GEN-LAST:event_guardarEquipo1MouseClicked

    private void simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulacionActionPerformed
        // TODO add your handling code here:
        ejecutarSimular();
    }//GEN-LAST:event_simulacionActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        ejecutarEliminar();
    }//GEN-LAST:event_EliminarActionPerformed

    
    private boolean verificarNombre(String nombre){
        for(EquiposFutbol teamChamp: administrarUser.getChampions()){
            if(teamChamp.getNombre().equalsIgnoreCase(nombre)){
                return true;
            }
        }
        return false;
    }
    
    private void butonmod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonmod1MouseClicked
        // TODO add your handling code here:
         int pos = Integer.parseInt(tf_posEl.getText());
       try {
            administrarUser.cargarText();
            administrarUser.getChampions().remove(pos);
            administrarUser.escribirText();
            JOptionPane.showMessageDialog(null, "Borrado Exitosamente");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo borrar");
        }
    }//GEN-LAST:event_butonmod1MouseClicked

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        // TODO add your handling code here:
        ejecutarCargarArchivo();
        File texto=null;
        FileReader fr=null;
        BufferedReader br=null;
        
        try{
            texto=new File ("./Text.txt");
            fr=new FileReader(texto);
            br=new BufferedReader(fr);
            String Linea;
            DefaultTableModel mob = new DefaultTableModel();
            mob.addColumn("Dato.txt");
            while((Linea=br.readLine())!=null){
           mob.addRow(new String[]{Linea});
           
            }
          tablitaCarga.setModel(mob);
        }
        catch(IOException e){
            
        }
       
    
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void botonSimularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSimularMouseClicked
        // TODO add your handling code here:
        if(boxEquipo1.getSelectedIndex()>=0 && boxEquipo2.getSelectedIndex()>=0){
            if(boxEquipo1.getSelectedItem()!=boxEquipo2.getSelectedItem()){
                int goles1,goles2;
                goles1=num.nextInt(10);
                goles2=num.nextInt(10);
                EquiposFutbol team1= administrarUser.getChampions().get(boxEquipo1.getSelectedIndex());
                EquiposFutbol team2= administrarUser.getChampions().get(boxEquipo2.getSelectedIndex());
                
                golEquipo1.setText(String.valueOf(goles1));
                golEquipo2.setText(String.valueOf(goles2));
                       
                
                team1.setPartidosJugados(team1.getPartidosJugados()+1);
                team2.setPartidosJugados(team2.getPartidosJugados()+1);
                
                if(goles1>goles2){
                    team1.setPartidosGanados(team1.getPartidosGanados()+1);
                    team2.setPartidosGanados(team2.getPartidosPerdidos()+1);
                    team1.setPuntos(team1.getPuntos()+3);
                    JOptionPane.showMessageDialog(null,"El ganador es "+ team1.getNombre());
                }
                else if(goles1<goles2){
                    team1.setPartidosGanados(team1.getPartidosGanados()+1);
                    team2.setPartidosGanados(team2.getPartidosPerdidos()+1);
                    team1.setPuntos(team1.getPuntos()+3);
                    JOptionPane.showMessageDialog(null,"El ganador es "+ team1.getNombre());
                }
                else if(goles1==goles2){
                    team1.setPartidosEmpatados(team1.getPartidosEmpatados()+1);
                    team2.setPartidosEmpatados(team2.getPartidosEmpatados()+1);   
                    team1.setPuntos(team1.getPuntos()+1);
                    team2.setPuntos(team1.getPuntos()+1);
                    JOptionPane.showMessageDialog(null,team1.getNombre()+ " y " + team2.getNombre()+ " Empataron ");
                }
                
                team1.setGolesFavor(team1.getGolesFavor() +goles1);
                team1.setGolesContra(team1.getGolesContra()+goles2);
                team1.setGolesDiferencia(team1.getGolesDiferencia()+(team1.getGolesFavor()-team1.getGolesContra()));
                
                 team2.setGolesFavor(team2.getGolesFavor() +goles1);
                team2.setGolesContra(team2.getGolesContra()+goles2);
                team2.setGolesDiferencia(team2.getGolesDiferencia()+(team2.getGolesFavor()-team2.getGolesContra()));
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccione los equipos porfavor");
            }
        }
        
    }//GEN-LAST:event_botonSimularMouseClicked

    private void tablaPosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaPosicionesActionPerformed
        // TODO add your handling code here:
        ejecutarTablaPosiciones();
        ArreglarTabla();
        File texto=null;
        FileReader fr=null;
        BufferedReader br=null;
        
        try{
            texto=new File ("./Text.txt");
            fr=new FileReader(texto);
            br=new BufferedReader(fr);
            String Linea;
            DefaultTableModel mob = new DefaultTableModel();
            mob.addColumn("Dato.txt");
            while((Linea=br.readLine())!=null){
           mob.addRow(new String[]{Linea});
           
            }
          tablitaCarga.setModel(mob);
        }
        catch(IOException e){
            
        }
        
    }//GEN-LAST:event_tablaPosicionesActionPerformed
    
    
    private void ArreglarTabla(){
        EquiposFutbol arreglo[]=new EquiposFutbol[equipos.size()];
        for(int i=0;i<equipos.size();i++){
            arreglo[i]=equipos.get(i);
        }
        for(int i=0;i<arreglo.length-1;i++){
            int ind=i;
            for(int j=0;j<arreglo.length;j++){
            int pot=j;
            if(arreglo[ind].getPuntos()<arreglo[pot].getPuntos()){
                ind=j;
               }
            }
            EquiposFutbol menor=arreglo[ind];
            arreglo[ind]=arreglo[i];
            arreglo[i]=menor;
        }
        
        equipos.clear();
        for(int i=0;i<arreglo.length;i++){
            equipos.add(arreglo[arreglo.length-(i+1)]);
        }
        
    }
    private void ejecutarTablaPosiciones(){
        ventanaTabla.setModal(true);
        ventanaTabla.pack();
        ventanaTabla.setLocationRelativeTo(this);
        ventanaTabla.setVisible(true);
    }
    
    private void ejecutarCargarArchivo(){
        ventanaCargarArchivo.setModal(true);
        ventanaCargarArchivo.pack();
        ventanaCargarArchivo.setLocationRelativeTo(this);
        ventanaCargarArchivo.setVisible(true);
    }
    private void ejecutarEliminar(){
        ventanaEliminar.setModal(true);
        ventanaEliminar.pack();
        ventanaEliminar.setLocationRelativeTo(this);
        ventanaEliminar.setVisible(true);
    }
    private void ejecutarModificar(){
        ventanaModificar.setModal(true);
        ventanaModificar.pack();
        ventanaModificar.setLocationRelativeTo(this);
        ventanaModificar.setVisible(true);
    }
    private void ejecutarSimular(){
        ventanaSimular.setModal(true);
        ventanaSimular.pack();
        ventanaSimular.setLocationRelativeTo(this);
        ventanaSimular.setVisible(true);
    }
   private void ejecutarCrear(){
        ventanaCrear.setModal(true);
        ventanaCrear.pack();
        ventanaCrear.setLocationRelativeTo(this);
        ventanaCrear.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<EquiposFutbol> equipos=new ArrayList();
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Crear;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTextField NombreEquipo;
    private javax.swing.JTextField NombreEquipomod;
    private javax.swing.JMenuBar barra;
    private javax.swing.JButton botonSimular;
    private javax.swing.JComboBox<String> boxEquipo1;
    private javax.swing.JComboBox<String> boxEquipo2;
    private javax.swing.JButton butonmod;
    private javax.swing.JButton butonmod1;
    private javax.swing.JMenuItem cargarArchivo;
    private javax.swing.JLabel golEquipo1;
    private javax.swing.JLabel golEquipo2;
    private javax.swing.JButton guardarEquipo;
    private javax.swing.JButton guardarEquipo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabeltextmod;
    private javax.swing.JLabel jLabeltextmod1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelnombre1;
    private javax.swing.JMenuItem simulacion;
    private javax.swing.JMenu tabEquipos;
    private javax.swing.JMenu tabPartidos;
    private javax.swing.JMenuItem tablaPosiciones;
    private javax.swing.JTable tablitaCarga;
    private javax.swing.JTextField tf_pos;
    private javax.swing.JTextField tf_posEl;
    private javax.swing.JDialog ventanaCargarArchivo;
    private javax.swing.JDialog ventanaCrear;
    private javax.swing.JDialog ventanaEliminar;
    private javax.swing.JDialog ventanaModificar;
    private javax.swing.JDialog ventanaSimular;
    private javax.swing.JDialog ventanaTabla;
    // End of variables declaration//GEN-END:variables
private AdministrarUserText administrarUser=new AdministrarUserText("./Text.txt");
private Random num=new Random();
}
